### ISSUE TITLE
Can you explain a bit about the Largegrid Env?

### ISSUE THREAD

**Issue by Yyh3** [cts198859/deeprl_dist#1]
Thanks for sharing the code. It really helps me understand the paper and algorithms. But I can't really figure out what the largegrid Env is about? Is this an environment that others define in paper?If no, can you do me a favor and explain this a bit. Otherwise, may you point out what the paper is.
Thanks again for offering your hands.

**Comment by cts198859** [comment]
Thanks for your interest. This repo is still under construction and I will add more details in the future. Regarding the largegrid Env, it is a traffic signal control environment borrowed from another repo https://github.com/cts198859/deeprl_signal_control. Hope this answers your question.
